"""initial schema

Revision ID: dea98e341b0c
Revises: 
Create Date: 2026-04-08 23:23:40.682966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dea98e341b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('undertone', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hex_palette', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('shade_name', sa.Text(), nullable=True),
    sa.Column('hex_code', sa.Text(), nullable=True),
    sa.Column('swatch_url', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('retailer', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.Text(), nullable=False),
    sa.Column('subscription_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('primary_season_id', sa.UUID(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_season_id'], ['color_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('product_season_map',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['color_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'season_id'),
    sa.UniqueConstraint('product_id', 'season_id', name='uq_product_season')
    )
    op.create_table('user_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('raw_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selfie_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['color_seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_saved_products',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product')
    )
    op.create_table('influencer_season_map',
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['color_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('influencer_id', 'season_id'),
    sa.UniqueConstraint('influencer_id', 'season_id', name='uq_influencer_season')
    )
    op.create_table('lip_combos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('mention_type', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lip_combo_items',
    sa.Column('combo_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['lip_combos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('combo_id', 'product_id'),
    sa.UniqueConstraint('combo_id', 'product_id', name='uq_combo_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lip_combo_items')
    op.drop_table('product_mentions')
    op.drop_table('lip_combos')
    op.drop_table('influencer_season_map')
    op.drop_table('user_saved_products')
    op.drop_table('user_analysis_results')
    op.drop_table('product_season_map')
    op.drop_table('influencers')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('color_seasons')
    # ### end Alembic commands ###
